
### USER REGISTRATION
INSERT INTO VEHICLE_MANAGEMENT.VUSER
(USER_ID, EMAIL, NAME, PASSWORD)
VALUES(6834, 'harshrajput@gmail.com', 'harsh', 'harsh@124');

###VEHICLE REGISTRATION
INSERT INTO VEHICLE_MANAGEMENT.VEHICLE
(VEHICLE_ID, LICENSE_PLATE, "TYPE", USER_USER_ID)
VALUES(602, 'Jh123441', 'CAR', 6834);

###BOOKING SLOT
INSERT INTO VEHICLE_MANAGEMENT.BOOKING
(BOOKING_ID, END_TIME, START_TIME, SLOT_SLOT_ID, USER_USER_ID, VEHICLE_VEHICLE_ID)
VALUES(1619, '2025-07-18 16:00:00.000', '2025-07-18 14:00:00.000', 5252, 9641, 5602);

#PAYMENT
INSERT INTO VEHICLE_MANAGEMENT.PAYMENT
(PAYMENT_ID, AMOUNT, STATUS, BOOKING_BOOKING_ID)
VALUES(5252, 100.0, 'PAID', 1619);

#REPORTS

INSERT INTO VEHICLE_MANAGEMENT.REPORT
(REPORT_ID, DESCRIPTION, USER_USER_ID)
VALUES(152, 'Parking slot was occupied by another vehicle.', 6834);

#PARKING SLOT
INSERT INTO VEHICLE_MANAGEMENT.PARKING_SLOT
(SLOT_ID, STATUS, "TYPE")
VALUES(5252, 'BOOKED', 'CAR');